### ISSUE TITLE
generateCode > Can't override classpath with an empty path

### ISSUE THREAD

**Issue by Favorlock** [freefair/gradle-plugins#191]
Getting the message seen in the title when generateCode is run.

Java 13 with Java 8 target
Gradle 6.1.1
code-generate/-api 5.0.0-rc6

**Comment by Frisch12** [comment]
Hi Favorlock,

have you specified any codeGenerator in your dependencies yet? You can view an example for the usage here: https://github.com/freefair/gradle-plugins/tree/master/examples/code-generator

Otherwise could you please share your configuration and/or a test project so I can investigate your problem? 

Kind regards, 
Dennis

**Comment by Favorlock** [comment]
I think it may be the codeGenerator part missing from my dependencies. I had assumed that I could make a generator in the same project and that it would detect the generator classes.

**Comment by Favorlock** [comment]
That was definitely the case.
