### ISSUE TITLE
Method Not Found error

### ISSUE THREAD

**Issue by innovationhub-asia** [freefair/gradle-plugins#257]
Hey,

I am using the post-compile plugin, with gradle 6.5.1, to integrate micometer aspects into my projects, and the build.gradle looks something like:

```gradle
plugins {
    id "io.freefair.aspectj.post-compile-weaving" version "5.1.1"
}

compileJava.ajc.options.compilerArgs += "-showWeaveInfo"
compileJava.ajc.options.compilerArgs += "-verbose"

allprojects {
    apply plugin: "io.freefair.aspectj.post-compile-weaving"

    dependencies {
        aspect "io.micrometer:micrometer-core:1.5.4"
    }
}
```

The build is working just fine, I can see aspectj info printouts. But when I run tests that include the use of the aspects, I get the following error:

```
java.lang.NoSuchMethodError: io.micrometer.core.aop.TimedAspect.aspectOf()Lio/micrometer/core/aop/TimedAspect;
```

It seems like files are generated but not included in the classpath. What am I missing?

The micrometer aspects are defined as:

```java
@Aspect
public class TimedAspect {}
```

**Comment by larsgrefer** [comment]
The `io.micrometer.core.aop.TimedAspect` seems to be on the classpath (if it wasn't, you'd get a NoClassDefFoundError instead of your NoSuchMethodError)

The `io.micrometer.core.aop.TimedAspect` class in the micrometer-core jar, isn't a completely compiled binary aspect. (It hasn't been processed by ajc).
I assume ist's only intended to be used with load-time-weaving or spring-aop

**Comment by innovationhub-asia** [comment]
Thank you
