### ISSUE TITLE
Support for protobuf-gradle-plugin with lombok

### ISSUE THREAD

**Issue by kun-zhou** [freefair/gradle-plugins#315]
I have a project using both and it seems like the generated code from the protobuf plugin isn't getting compiled. The protobuf plugin works by adding the generated code to the source sets. It looks like the compileJava source is empty when Gradle first reads the `build.gradle` file and then replaced with code from the lombok build dir later.

I tried reading the plugin's code (a bit too difficult for me at the moment), could you please help me understand the what is going on here? Or if you are not familiar with the particular plugin, what you think is going on? Thank you so much!

**Comment by larsgrefer** [comment]
Can you provide an example project which replicates the issue?

**Comment by kun-zhou** [comment]
Sure. I uploaded a MWE to https://github.com/kun-zhou/mwe-lombok-issue-315. Turns out it also has to do with the checker framework.

**Comment by kun-zhou** [comment]
@larsgrefer Let me know if I can help with anything. Would love to hear what you think is the issue so I have a direction to work on. Thanks for all the work on these fine plugins!

**Comment by larsgrefer** [comment]
This bug seems to be introduced by the `org.checkerframework` Gradle plugin which modifies the inputs of the compileJava task in presence of my Lombok plugin:

https://github.com/kelloggm/checkerframework-gradle-plugin/blob/def758bc02a10b13596134922129ecc7ca8354f5/src/main/groovy/org/checkerframework/gradle/plugin/CheckerFrameworkPlugin.groovy#L172

On the other hand: What the `org.checkerframework` plugin tries to do would actually work, if the protobuf gradle plugin would attach the generated code to the source set instead of just the compile task

**Comment by larsgrefer** [comment]
Here is the corresponding issue for the protobuf-gradle-plugin: https://github.com/google/protobuf-gradle-plugin/issues/474
