### ISSUE TITLE
Lombok.config file are not generated with version 6.1.0 of the gradle plugin

### ISSUE THREAD

**Issue by alexanderlindholm** [freefair/gradle-plugins#379]
With plugin version 5.3.3.3 a lombok.config file is autogenerated for the gradle project. But with version 6.1.0 it is not. I am not sure how to provide more information around this issue.

**Comment by larsgrefer** [comment]
This is actually intended. I was never quite satisfied with the configuration generation feature and also received some issues about it (#249 #307 #311)

Since Version 6.x the lombok.config files are not generated by the plugin anymore but the user is expected to supply the configuration _manually_ as documented here: https://projectlombok.org/features/configuration

The plugin will make sure the compilation tasks respect the config files in their up-to-date checks and will warn you if a recommended configuration is not set (e.g. using spotbugs without `lombok.extern.findbugs.addSuppressFBWarnings = true`)

The config files generated by 5.x should still work fine (but you might have to add them to VCS)

**Comment by henry-hub** [comment]
I think we can provide an extended attribute to decide whether to enable this feature.

**Comment by martmagi** [comment]
You definitely need to highlight this in the documentation. I had to upgrade Lombok for our Java 11 -> 17 upgrade and was stuck for entire day with my changes working locally (where I had the autogenerated `lombok.config` but failing in Jenkins (where there was no `lombok.config` but I don't have access to it). 

Thank you for posting this issue as I would likely have never figured this out on my own.

**Comment by habizzle** [comment]
After having upgraded from v5 to v6 I have ran into the same problem. It is especially hard to find out, as it was only failing on CI (as the auto-generated config was not checked-in).

But do I understand correctly, that the `config`-Property in `LombokExtension` is completely ignored in v6? Why did you not just remove it instead of deprecating it?

**Comment by ClaudioConsolmagno** [comment]
Yep, we also got caught by this upgrading our projects recently. We have 20+ projects we are slowly migrating from from gradle 5 to 7 and new versions of lombok. Knowing this now, we'll need to make sure to add `lombok.config` to all repos when upgrading.
Ideally, we would want either:
- Some setting to generate the "default" `lombok.config`. E.g.:
   ```
   lombok {
      generateLombokConfig: true // false by default
   }
   ```
- Some setting to point to a different location where the repo's `lombok.config` is located. E.g.:
   ```
   lombok {
      lombokConfig: file("${project.rootDir}") // This is the default and can be changed
   }
   ```
Having either of the those above would allows us to configure lombok globally without having to change all projects.

Just a thought.

**Comment by larsgrefer** [comment]
@ClaudioConsolmagno What settings do you need to set in your lombok configuration?

if you need the same configuration for all your projects, you could just put one `lombok.config` file in a common parent directory.

**Comment by ClaudioConsolmagno** [comment]
I'm setting the following settings which is what was done by default with previous versions of the plugin:
```
config.stopBubbling = true
lombok.addLombokGeneratedAnnotation = true
lombok.extern.findbugs.addSuppressFBWarnings = true
```

We have a separate repo per project so there's no "parent" directory. What we do have is a common config git submodule that we use for common config files such as spotbugs, checkstyle, etc. With those plugins I can point to those configs but not for lombok. The less painful way we found was to put the lombok.config in the submodule and hook it up so that the file is copied on build to the root project directory.

**Comment by larsgrefer** [comment]
@ClaudioConsolmagno You could just import your common config from the root `lombok.config` of each repo:

```properties
import common-submodule/lombok.config
config.stopBubbling = true
```

https://projectlombok.org/features/configuration

**Comment by ClaudioConsolmagno** [comment]
That's the thing, we don't have `lombok.config` in any of our repos, the file is even in the `.gitignore` file. They all previously relied on the build time generated `lombok.config`. So as part of our gradle (and lombok) migration we have to create these files somehow, manually or otherwise.

Don't get me wrong, I agree that `lombok.config` generation should never have been done by default by the old version of the plugin. But it would be nice if there was a way to customise the file or location of the file via the plugin as I mention in previous comment.

**Comment by larsgrefer** [comment]
Making the config location configurable in build.gradle makes no sense because Gradle cannot tell Lombok where its configuration is. Lombok looks for its configuration itself, so it basically dictates, where the config files have to be, in order to be picked up.
