### ISSUE TITLE
v6.2.0 - Not adding @Generated annotations

### ISSUE THREAD

**Issue by overfullstack** [freefair/gradle-plugins#391]
Sample multi-module project: https://github.com/overfullstack/my-lab/tree/master/lombok-lab
Sample single module project: https://github.com/overfullstack/untitled

I have the following lombok.config:

```
config.stopBubbling = true
lombok.addLombokGeneratedAnnotation = true
lombok.extern.findbugs.addSuppressFBWarnings = true
```

But when I see the generated code in `build/generated/sources/delombok/java/main/...` I don't see `@Generated` annotations. This is affecting my Jacoco test coverage. Please help. Thanks.
(I observed from my single module project that `@Genearated` annotations are being added to classes in `build/classes/java/main/...` but not to `build/generated/sources/delombok/java/main/...`, is this a bug or expected?)

**Comment by larsgrefer** [comment]
This seems to be the default behavior of lombok (or de-lombok to be precise), so from my point of view, this is expected behavior.

If you think that annotations should be added to the delombok-ed source code as well, you should raise this concern here: https://github.com/projectlombok/lombok/issues
