### ISSUE TITLE
Circular dependency with `delombok` on 6.4.1

### ISSUE THREAD

**Issue by overfullstack** [freefair/gradle-plugins#498]
I upgraded lombok gradle plugin from 6.3.0 to 6.4.1, but now I get these errors.

```
Circular dependency between the following tasks:
:specs:delombok
\--- :specs:delombok (*)
```

It’s a small 3-module gradle project, please find it here: https://github.com/overfullstack/vader-root
I downgraded to 6.3.0 and these errors are gone. Can someone please help me what changed in 6.4.1 and how can I solve this. Thanks!

**Comment by Frisch12** [comment]
Hi @overfullstack 

Thank you for your issue submission.

I've created a small project that reproduces your issue https://github.com/freefair/delombok-error-498 
The problem is, that you set the srcDir for java and kotlin to the delombok task. 

As the delombok task already sets itself as src for the javadoc task you should be able to build your project just by remove the `kotlin.setSrcDirs(listOf(tasks.delombok))` and `java.setSrcDirs(listOf(tasks.delombok))`. 
Is that feasible for you?

Thanks, 
Dennis

**Comment by overfullstack** [comment]
Thanks @Frisch12 for looking into. Removing `java.setSrcDirs` resolved my issue. However, I had to keep `kotlin.setSrcDirs` because I want Kotlin compiler to depend on Delomboked code. Is there a better way to achieve it?

**Comment by Frisch12** [comment]
@overfullstack You can keep the `kotlin.setSrcDir` if it works for you.
