### ISSUE TITLE
aggregateJavadocJar creates an infinite file

### ISSUE THREAD

**Issue by mfnalex** [freefair/gradle-plugins#798]
Hello :)

I'm using the aggregate-javadoc-jar plugin like this: https://github.com/mfnalex/lunatic/blob/master/build.gradle

However, whenever I wanna build, it creates an infinite javadoc.jar in the root project's build/docs folder. The issue is that the javadoc.jar contains itself: 
![image](https://github.com/freefair/gradle-plugins/assets/1122571/f1461bb6-034e-4419-90cf-2684d9e91fb5)

The file is getting bigger and bigger while running aggregateJavadocJar until the hard disk is full or the process is cancelled. Am I doing something wrong?

Note: It DOES work fine on macOS, this issue seems to be reproducible on Windows. On Linux, I got reports from 2 people, where one person has the same issue, the other person doesn't. We were all using the gradle wrapper for 8.1.1

Any clue what might be causing this / any ideas for workarounds?

**Comment by Geolykt** [comment]
The cause of this problem is most likely <https://github.com/freefair/gradle-plugins/blob/master/maven-plugin/src/main/java/io/freefair/gradle/plugins/maven/javadoc/AggregateJavadocJarPlugin.java#L35-L37> which causes the destination directory be the same as in the directory from which the `Jar` task takes in the inputs.

A workaround can be applied by adding following code to the end of the buildscript:

```groovy
aggregateJavadocJar {
    getDestinationDirectory().set(file(getBuildDir().toPath().resolve("docs")))
}
```


I do not exactly know why MacOS isn't affected by this issue, but I assume that it is due to differences to when the OS commits files to disk.

**Comment by mfnalex** [comment]
That fixed it! Thank you so much, again <3

**Comment by larsgrefer** [comment]
Thanks for bringing this up again and especially to @Geolykt for finding the root of the problem.

I basically ignored, and then forgot about #640 because it "works on my machine" and I couldn't reproduce the problem.
Very interesting that it works on MacOS, fails on Windows and sometimes works/fails on Linux.

I'd suggest giving the new `io.freefair.aggregate-javadoc` Plugin a try, which was completely rewritten with Version 8.0.0 and provides both the javadoc and javadocJar Tasks. The `io.freefair.aggregate-javadoc-jar` plugin mentioned here is based on the pre-8.0.0 mechanism which has been moved to the `io.freefair.aggregate-javadoc-legacy` Plugin.

https://docs.freefair.io/gradle-plugins/8.x/reference/#_io_freefair_aggregate_javadoc

**Comment by mfnalex** [comment]
@larsgrefer thanks for the heads up. Unfortunately i had the same problem in version 8.0.1, but the fix mentioned above seems to work fine. I will close this issue now, have a nice day everyone :3

**Comment by mfnalex** [comment]
Oh you mentioned io.freefair.aggregate-javadoc, i didn’t realize its a different plugin. I‘ll give that a try soon, maybe tomorrow - I‘m currently just happy that everything‘s working for me right now haha
